name: smart_stock_counter
description: A smart stock counting application using object detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  http: ^1.1.0
  path: ^1.8.3
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  network_info_plus: ^4.0.0
  salomon_bottom_bar: ^3.3.2
  curved_navigation_bar: ^1.0.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-SemiBold.ttf
  uses-material-design: true
  assets:
    - assets/images/
